CREATE DATABASE NOOTEA1
GO

USE NOOTEA 
GO


CREATE TABLE DanhMucSP(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaDM VARCHAR(10) UNIQUE,
	TenDM NVARCHAR(50) NOT NULL,
	TrangThai INT DEFAULT 1
)
GO
CREATE TABLE Size(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaSize VARCHAR(10) UNIQUE,
	TenSize NVARCHAR(50) NOT NULL,
	Gia DECIMAL(20,0) DEFAULT 0,
	TrangThai INT DEFAULT 1
)
GO
CREATE TABLE SanPham(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaSP VARCHAR(10) UNIQUE,
	TenSP NVARCHAR(50) NOT NULL,
	Gia DECIMAL(20,0) DEFAULT 0,
	MoTa NVARCHAR(100) DEFAULT NULL,
	HinhAnh nvarchar(100) DEFAULT NULL,
	TrangThai INT DEFAULT 1,
	IDSize UNIQUEIDENTIFIER,
	IDDanhMuc UNIQUEIDENTIFIER,
	CONSTRAINT FK_SP_Size FOREIGN KEY(IDSize) REFERENCES Size(ID),
	CONSTRAINT FK_SP_DanhMucSP FOREIGN KEY(IDDanhMuc) REFERENCES DanhMucSP(ID)
)
GO


CREATE TABLE KhachHang(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaKH VARCHAR(30) UNIQUE,
	hoTen NVARCHAR(100) NOT NULL,
	gioiTinh NVARCHAR(10) DEFAULT NULL,
	SDT VARCHAR(30) DEFAULT NULL,
	diaChi NVARCHAR(100) DEFAULT NULL
)
GO
CREATE TABLE ChucVu(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaCV VARCHAR(10) UNIQUE,
	Ten NVARCHAR(100) NOT NULL
)
GO
CREATE TABLE NhanVien(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MANV nvarchar(30) unique,
	TaiKhoan VARCHAR(30) UNIQUE,
	MatKhau VARCHAR(MAX) DEFAULT NULL,
	HoTen NVARCHAR(100) NOT NULL,
	GioiTinh NVARCHAR(10) DEFAULT NULL,
	NgaySinh DATE DEFAULT NULL,
	SDT VARCHAR(30) DEFAULT NULL,
	DiaChi NVARCHAR(100) DEFAULT NULL,
	IDCV UNIQUEIDENTIFIER,
	CONSTRAINT FK_NV_CV FOREIGN KEY(IDCV) REFERENCES ChucVu(ID),
	TrangThai int NOT NULL
)
GO
CREATE TABLE HinhThucThanhToan(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MAHTTT VARCHAR(10) UNIQUE,
	Ten NVARCHAR(100) NOT NULL
)
GO
CREATE FUNCTION AUTO_MAHD()
RETURNS VARCHAR(7)
AS
BEGIN
	DECLARE @ID VARCHAR(7)
	IF (SELECT COUNT(MaHD) FROM HoaDon) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaHD, 5)) FROM HoaDon
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'HD0000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HD000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 THEN 'HD00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 999 THEN 'HD0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9999 THEN 'HD' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO
drop table HoaDon
CREATE TABLE HoaDon(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaHD VARCHAR(30) UNIQUE CONSTRAINT IDHD DEFAULT DBO.AUTO_MAHD(),
	IDNV UNIQUEIDENTIFIER,
	IDKH UNIQUEIDENTIFIER,
	NgayTao DATE DEFAULT NULL,
	tienThuaTraKhach DECIMAL(20,0) DEFAULT 0,
	
	TongTien DECIMAL(20,0) DEFAULT 0,
	ThanhToan DECIMAL(20,0) DEFAULT 0,
	IDHTTT UNIQUEIDENTIFIER,
	TrangThai NVARCHAR(50) NOT NULL,
	GhiChu NVARCHAR(100) DEFAULT NULL,
	CONSTRAINT FK_HD_NV FOREIGN KEY(IDNV) REFERENCES NhanVien(ID),
	CONSTRAINT FK_HD_KH FOREIGN KEY(IDKH) REFERENCES KhachHang(ID),
	CONSTRAINT FK_HD_HTTT FOREIGN KEY(IDHTTT) REFERENCES HinhThucThanhToan(ID)
)
GO
drop table HoaDonChiTiet
CREATE TABLE HoaDonChiTiet(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IDHD UNIQUEIDENTIFIER,
	IDSP UNIQUEIDENTIFIER,
	DonGia DECIMAL(20,0) DEFAULT 0,
	SoLuong INT NOT NULL,
	ThanhToan DECIMAL(20,0) DEFAULT 0,
	CONSTRAINT FK_HDCT_HD FOREIGN KEY(IDHD) REFERENCES HoaDon(ID),
	CONSTRAINT FK_HDCT_SP FOREIGN KEY(IDSP) REFERENCES SanPham(ID),
)
GO
SELECT * FROM HoaDon

